import { StrictMode, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import './styles.css';
import { api, ApiStation, Reservation as ApiReservation, Session as ApiSession } from './api';

type Connector = { id: string; type: string; power: number; price: number; available: boolean };
type Station = { id: string; name: string; address: string; lat: number; lng: number; connectors: Connector[] };
const demoStations: Station[] = [
  { id: 'long-beach-central', name: 'Long Beach Central', address: '100 Ocean Blvd, Long Beach, CA', lat: 33.7701, lng: -118.1937, connectors: [{ id: 'lb-ccs-1', type: 'CCS', power: 150, price: .42, available: true }, { id: 'lb-j1772-2', type: 'J1772', power: 11, price: .29, available: true }] },
  { id: 'shoreline-fast', name: 'Shoreline Fast Charge', address: '200 Aquarium Way, Long Beach, CA', lat: 33.7629, lng: -118.1928, connectors: [{ id: 'sl-ccs-1', type: 'CCS', power: 250, price: .49, available: false }] },
];
let lastStations = demoStations;
const normalize = (s: ApiStation): Station => ({ id: s.id, name: s.name, address: s.address || 'Address unavailable', lat: s.latitude ?? s.lat ?? 0, lng: s.longitude ?? s.lng ?? 0, connectors: s.connectors.map(c => ({ id: c.id, type: c.type, power: c.powerKw ?? c.power ?? 0, price: c.ratePerKwh ?? c.price ?? 0, available: c.available })) });
function statusMessage(error: unknown) { return error instanceof Error ? error.message : 'Something went wrong. Please try again.'; }
function Layout({ children }: { children: React.ReactNode }) { return <><header><Link to="/discover" className="brand">CHARGE<span>GRID</span></Link><nav><Link to="/activity">Activity</Link><Link to="/payment-method">Payment</Link><Link to="/login" className="nav-cta">Log in</Link></nav></header><main>{children}</main></>; }
function Feedback({ loading, error, retry }: { loading: boolean; error: string; retry?: () => void }) { return loading ? <p className="muted">Loading...</p> : error ? <div className="card info"><p className="muted">{error}</p>{retry && <button className="outline" onClick={retry}>Try again</button>}</div> : null; }
function Login() { const navigate = useNavigate(); return <section className="center-page"><div className="card auth"><p className="eyebrow">YOUR CHARGING NETWORK</p><h1>Power up, <i>without</i> the wait.</h1><p>Find a connector, reserve it for ten minutes, and get moving.</p><button onClick={() => navigate('/discover')}>Continue with Keycloak</button><small>Demo mode is enabled. Production login uses the configured OIDC client.</small></div></section>; }
function MapView({ stations }: { stations: Station[] }) { const mapElement = useRef<HTMLDivElement>(null); useEffect(() => { if (!mapElement.current) return; const map = new maplibregl.Map({ container: mapElement.current, style: 'https://demotiles.maplibre.org/style.json', center: [-118.1937, 33.7701], zoom: 12 }); map.addControl(new maplibregl.NavigationControl(), 'top-right'); stations.forEach(s => new maplibregl.Marker({ color: '#a4e96c' }).setLngLat([s.lng, s.lat]).setPopup(new maplibregl.Popup().setText(s.name)).addTo(map)); return () => map.remove(); }, [stations]); return <div className="map" ref={mapElement}/>; }
function Discover() { const [available, setAvailable] = useState(false); const [items, setItems] = useState(demoStations); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const load = () => { setLoading(true); api.nearby().then(data => { const next = data.map(normalize); lastStations = next; setItems(next); setError(''); }).catch(() => { setItems(demoStations); setError('API unavailable. Showing demo stations.'); }).finally(() => setLoading(false)); }; useEffect(load, []); const visible = items.filter(s => !available || s.connectors.some(c => c.available)); return <section><div className="page-heading"><div><p className="eyebrow">DISCOVER</p><h1>Find your next charge.</h1></div><button className="outline" onClick={() => navigator.geolocation?.getCurrentPosition(p => api.nearby(p.coords.latitude, p.coords.longitude).then(data => setItems(data.map(normalize))).catch(() => undefined))}>◎ Use my location</button></div><div className="searchbar"><input placeholder="Search a city or address"/><select><option>All connectors</option><option>CCS</option><option>J1772</option></select><label><input type="checkbox" checked={available} onChange={e => setAvailable(e.target.checked)} /> Available now</label></div><Feedback loading={loading} error={error} retry={load}/><div className="discover-grid"><MapView stations={visible}/><div className="station-list"><p className="muted">{visible.length} stations nearby</p>{visible.map(s => <Link className="station-card" to={`/stations/${s.id}`} key={s.id}><div><h3>{s.name}</h3><p>{s.address}</p></div><strong>{s.connectors.filter(c => c.available).length}<small> available</small></strong><span>›</span></Link>)}</div></div></section>; }
function findStation(id: string) { return lastStations.find(s => s.id === id) || demoStations.find(s => s.id === id); }
function StationDetails() { const { id = '' } = useParams(); const navigate = useNavigate(); const [station, setStation] = useState<Station | undefined>(() => findStation(id)); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); useEffect(() => { api.station(id).then(data => { const next = normalize(data); lastStations = [...lastStations.filter(s => s.id !== next.id), next]; setStation(next); }).catch(e => { if (!findStation(id)) setError(statusMessage(e)); }).finally(() => setLoading(false)); }, [id]); if (!station) return <section className="narrow"><Feedback loading={loading} error={error || 'Station not found.'}/><Link to="/discover" className="back">← Back to discovery</Link></section>; const reserve = (connectorId: string) => { setBusy(true); setError(''); api.reserve(connectorId).then(r => navigate(`/reservations/${r.id}`)).catch(e => setError(statusMessage(e))).finally(() => setBusy(false)); }; return <section className="narrow"><Link to="/discover" className="back">← Back to discovery</Link><p className="eyebrow">STATION DETAILS</p><h1>{station.name}</h1><p className="lead">{station.address}</p><div className="actions"><button className="outline" onClick={() => navigator.clipboard?.writeText(station.address)}>Copy address</button><a className="outline button-link" href={`https://www.google.com/maps/dir/?api=1&destination=${station.lat},${station.lng}`} target="_blank">Open in Google Maps ↗</a></div>{loading && <p className="muted">Refreshing station details...</p>}{error && <p className="muted">{error}</p>}<h2>Choose a connector</h2>{station.connectors.map(c => <div className="connector" key={c.id}><div><b>{c.type}</b><p>{c.power} kW maximum · ${c.price.toFixed(2)} / kWh</p></div><span className={c.available ? 'available' : 'unavailable'}>{c.available ? 'Available' : 'In use'}</span>{c.available && <button disabled={busy} onClick={() => reserve(c.id)}>{busy ? 'Reserving...' : 'Reserve'}</button>}</div>)}</section>; }
function Reservation() { const { id = '' } = useParams(); const navigate = useNavigate(); const [reservation, setReservation] = useState<ApiReservation | null>(null); const [code, setCode] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { api.reservation(id).then(setReservation).catch(e => setError(statusMessage(e))).finally(() => setLoading(false)); }, [id]); const start = () => { setError(''); api.verifyStart(id, code).then(s => navigate(`/sessions/${s.id}`)).catch(e => setError(statusMessage(e))); }; const station = lastStations.find(s => s.connectors.some(c => c.id === reservation?.connectorId)) || demoStations[0]; const connector = station.connectors.find(c => c.id === reservation?.connectorId) || station.connectors[0]; return <section className="narrow"><Feedback loading={loading} error={error}/>{reservation && <><p className="eyebrow">RESERVATION {reservation.status}</p><h1>Your connector is waiting.</h1><div className="timer">09:42<small> remaining</small></div><div className="card info"><b>{connector.type} · {connector.power} kW</b><p>{station.name}<br/>{station.address}</p></div><label className="code-label">Enter start code<input value={code} onChange={e => setCode(e.target.value)} placeholder="6-digit code" maxLength={6}/></label>{error && <p className="muted">{error}</p>}<button className="button-link primary" disabled={code.length !== 6} onClick={start}>Start charging</button></>}</section>; }
function Session() { const { id = '' } = useParams(); const [session, setSession] = useState<ApiSession | null>(null); const [code, setCode] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); useEffect(() => { api.session(id).then(setSession).catch(e => setError(statusMessage(e))).finally(() => setLoading(false)); }, [id]); const stop = () => api.verifyStop(id, code).then(() => window.location.assign('/activity')).catch(e => setError(statusMessage(e))); return <section className="narrow"><Feedback loading={loading} error={error}/>{session && <><div className="live"><span>● LIVE SESSION</span><strong>{session.status}</strong></div><h1>Charging session</h1><div className="metrics"><div><small>ENERGY</small><b>{session.meterKwh.toFixed(2)} <i>kWh</i></b></div><div><small>SESSION</small><b>{session.id.slice(0, 8)}</b></div><div><small>EST. COST</small><b>${Number(session.cost).toFixed(2)}</b></div></div><label className="code-label">Enter stop code<input value={code} onChange={e => setCode(e.target.value)} placeholder="6-digit code" maxLength={6}/></label>{error && <p className="muted">{error}</p>}<button className="button-link primary" disabled={code.length !== 6} onClick={stop}>Stop charging</button></>}</section>; }
function Activity() { return <section className="narrow"><p className="eyebrow">ACTIVITY</p><h1>Your charging history.</h1><div className="card history"><div><b>Long Beach Central</b><p>Charging activity</p></div></div></section>; }
function Payment() { return <section className="narrow"><p className="eyebrow">PAYMENT METHOD</p><h1>Keep your charge moving.</h1><div className="card payment"><div className="fake-card"><b>VISA</b><span>•••• 4242</span></div><label><input type="checkbox" defaultChecked/> I consent to usage-based charging after a session.</label><button className="primary">Save payment method</button><p className="muted">Cards are securely collected by Stripe Elements. ChargeGrid never stores card numbers or CVC.</p></div></section>; }
function Simulator() { const { id = '' } = useParams(); const [data, setData] = useState<any>(null); const [kwh, setKwh] = useState('1'); const [error, setError] = useState(''); const load = () => api.simulator(id).then(setData).catch(e => setError(statusMessage(e))); useEffect(() => { load(); }, [id]); const meter = (sessionId: string) => api.meter(sessionId, Number(kwh)).then(load).catch(e => setError(statusMessage(e))); return <section className="narrow simulator"><p className="eyebrow">STATION SIMULATOR · OPERATOR DISPLAY</p><h1>Station simulator</h1><p className="lead">Physical charger control panel</p>{error && <div className="card info"><p className="muted">{error}</p><button className="outline" onClick={load}>Try again</button></div>}{data && <div className="card info"><small>ACTIVE RESERVATIONS</small>{data.reservations.map((r: any) => <p key={r.id}>{r.connectorId} · {r.status}<br/><b className="sim-code">{r.startCode}</b></p>)}<small>ACTIVE SESSIONS</small>{data.sessions.map((s: any) => <div key={s.id}><p>{s.id} · {s.meterKwh.toFixed(2)} kWh</p><input type="number" min="0.01" step="0.01" value={kwh} onChange={e => setKwh(e.target.value)}/><button className="outline" onClick={() => meter(s.id)}>Add meter reading</button><p><b className="sim-code stop">{s.stopCode}</b></p></div>)}</div>}</section>; }
function App() { return <Layout><Routes><Route path="/login" element={<Login/>}/><Route path="/discover" element={<Discover/>}/><Route path="/stations/:id" element={<StationDetails/>}/><Route path="/reservations/:id" element={<Reservation/>}/><Route path="/sessions/:id" element={<Session/>}/><Route path="/activity" element={<Activity/>}/><Route path="/payment-method" element={<Payment/>}/><Route path="/admin/stations/:id/simulator" element={<Simulator/>}/><Route path="*" element={<Discover/>}/></Routes></Layout>; }
createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><App/></BrowserRouter></StrictMode>);
