import { StrictMode, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useNavigate } from 'react-router-dom';
import maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import './styles.css';

type Connector = { id: string; type: string; power: number; price: number; available: boolean };
type Station = { id: string; name: string; address: string; lat: number; lng: number; connectors: Connector[] };
const stations: Station[] = [
  { id: 'long-beach-central', name: 'Long Beach Central', address: '100 Ocean Blvd, Long Beach, CA', lat: 33.7701, lng: -118.1937, connectors: [{ id: 'lb-ccs-1', type: 'CCS', power: 150, price: .42, available: true }, { id: 'lb-j1772-2', type: 'J1772', power: 11, price: .29, available: true }] },
  { id: 'shoreline-fast', name: 'Shoreline Fast Charge', address: '200 Aquarium Way, Long Beach, CA', lat: 33.7629, lng: -118.1928, connectors: [{ id: 'sl-ccs-1', type: 'CCS', power: 250, price: .49, available: false }] }
];

function Layout({ children }: { children: React.ReactNode }) { return <><header><Link to="/discover" className="brand">CHARGE<span>GRID</span></Link><nav><Link to="/activity">Activity</Link><Link to="/payment-method">Payment</Link><Link to="/login" className="nav-cta">Log in</Link></nav></header><main>{children}</main></>; }
function Login() { const navigate = useNavigate(); return <section className="center-page"><div className="card auth"><p className="eyebrow">YOUR CHARGING NETWORK</p><h1>Power up, <i>without</i> the wait.</h1><p>Find a connector, reserve it for ten minutes, and get moving.</p><button onClick={() => navigate('/discover')}>Continue with Keycloak</button><small>Demo mode is enabled. Production login uses the configured OIDC client.</small></div></section>; }
function MapView() { const mapElement = useRef<HTMLDivElement>(null); useEffect(() => { if (!mapElement.current) return; const map = new maplibregl.Map({ container: mapElement.current, style: 'https://demotiles.maplibre.org/style.json', center: [-118.1937, 33.7701], zoom: 12 }); map.addControl(new maplibregl.NavigationControl(), 'top-right'); stations.forEach(station => new maplibregl.Marker({ color: '#a4e96c' }).setLngLat([station.lng, station.lat]).setPopup(new maplibregl.Popup().setText(station.name)).addTo(map)); return () => map.remove(); }, []); return <div className="map" ref={mapElement}/>; }
function Discover() { const [available, setAvailable] = useState(false); return <section><div className="page-heading"><div><p className="eyebrow">DISCOVER</p><h1>Find your next charge.</h1></div><button className="outline" onClick={() => navigator.geolocation?.getCurrentPosition(() => undefined)}>◎ Use my location</button></div><div className="searchbar"><input placeholder="Search a city or address"/><select><option>All connectors</option><option>CCS</option><option>J1772</option></select><label><input type="checkbox" checked={available} onChange={e => setAvailable(e.target.checked)} /> Available now</label></div><div className="discover-grid"><MapView/><div className="station-list"><p className="muted">{stations.length} stations nearby</p>{stations.filter(s => !available || s.connectors.some(c => c.available)).map(s => <Link className="station-card" to={`/stations/${s.id}`} key={s.id}><div><h3>{s.name}</h3><p>{s.address}</p></div><strong>{s.connectors.filter(c => c.available).length}<small> available</small></strong><span>›</span></Link>)}</div></div></section>; }
function StationDetails() { const station = stations[0]; const navigate = useNavigate(); return <section className="narrow"><Link to="/discover" className="back">← Back to discovery</Link><p className="eyebrow">STATION DETAILS</p><h1>{station.name}</h1><p className="lead">{station.address}</p><div className="actions"><button className="outline" onClick={() => navigator.clipboard?.writeText(station.address)}>Copy address</button><a className="outline button-link" href={`https://www.google.com/maps/dir/?api=1&destination=${station.lat},${station.lng}`} target="_blank">Open in Google Maps ↗</a></div><h2>Choose a connector</h2>{station.connectors.map(c => <div className="connector" key={c.id}><div><b>{c.type}</b><p>{c.power} kW maximum · ${c.price.toFixed(2)} / kWh</p></div><span className={c.available ? 'available' : 'unavailable'}>{c.available ? 'Available' : 'In use'}</span>{c.available && <button onClick={() => navigate('/reservations/demo-reservation')}>Reserve</button>}</div>)}</section>; }
function Reservation() { return <section className="narrow"><p className="eyebrow">RESERVATION CONFIRMED</p><h1>Your connector is waiting.</h1><div className="timer">09:42<small> remaining</small></div><div className="card info"><b>CCS · 150 kW</b><p>Long Beach Central<br/>100 Ocean Blvd, Long Beach, CA</p><div className="actions"><button className="outline" onClick={() => navigator.clipboard?.writeText('100 Ocean Blvd, Long Beach, CA')}>Copy address</button><a className="outline button-link" href="https://www.google.com/maps/dir/?api=1&destination=33.7701,-118.1937" target="_blank">Open Google Maps ↗</a></div></div><label className="code-label">Enter start code<input placeholder="6-digit code" maxLength={6}/></label><Link className="button-link primary" to="/sessions/demo-session">Start charging</Link><button className="text-button">Cancel reservation</button></section>; }
function Session() { return <section className="narrow"><div className="live"><span>● LIVE SESSION</span><strong>Charging now</strong></div><h1>Long Beach Central</h1><div className="metrics"><div><small>ENERGY</small><b>8.42 <i>kWh</i></b></div><div><small>SPEED</small><b>112 <i>kW</i></b></div><div><small>EST. COST</small><b>$3.54</b></div></div><div className="progress"><span style={{ width: '38%' }}/></div><p className="muted">Elapsed time · 04:32</p><label className="code-label">Enter stop code<input placeholder="6-digit code" maxLength={6}/></label><Link className="button-link primary" to="/activity">Stop charging</Link></section>; }
function Activity() { return <section className="narrow"><p className="eyebrow">ACTIVITY</p><h1>Your charging history.</h1><div className="card history"><div><b>Long Beach Central</b><p>Today · 8.42 kWh</p></div><strong>$3.54 <small className="paid">PAID</small></strong></div><div className="card history"><div><b>Shoreline Fast Charge</b><p>Aug 28 · 21.10 kWh</p></div><strong>$9.87 <small className="paid">PAID</small></strong></div></section>; }
function Payment() { return <section className="narrow"><p className="eyebrow">PAYMENT METHOD</p><h1>Keep your charge moving.</h1><div className="card payment"><div className="fake-card"><b>VISA</b><span>•••• 4242</span></div><label><input type="checkbox" defaultChecked/> I consent to usage-based charging after a session.</label><button className="primary">Save payment method</button><p className="muted">Cards are securely collected by Stripe Elements. ChargeGrid never stores card numbers or CVC.</p></div></section>; }
function Simulator() { return <section className="narrow simulator"><p className="eyebrow">STATION SIMULATOR · OPERATOR DISPLAY</p><h1>Long Beach Central</h1><p className="lead">CCS connector 1 · Physical charger control panel</p><div className="card info"><small>START CODE · RESERVATION ACTIVE</small><div className="sim-code">482917</div><small>STOP CODE · GENERATED WHEN CHARGING STARTS</small><div className="sim-code stop">731204</div><p className="muted">These codes are shown only on the charger display. Never expose them through the driver API.</p></div></section>; }
function App() { return <Layout><Routes><Route path="/login" element={<Login/>}/><Route path="/discover" element={<Discover/>}/><Route path="/stations/:id" element={<StationDetails/>}/><Route path="/reservations/:id" element={<Reservation/>}/><Route path="/sessions/:id" element={<Session/>}/><Route path="/activity" element={<Activity/>}/><Route path="/payment-method" element={<Payment/>}/><Route path="/admin/stations/:id/simulator" element={<Simulator/>}/><Route path="*" element={<Discover/>}/></Routes></Layout>; }
createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><App/></BrowserRouter></StrictMode>);
